export const ADD_KEG = 'ADD_KEG';
export const DELETE_KEG = 'DELETE_KEG';
export const POUR_PINT = 'POUR_PINT';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const SET_FORM_FALSE = 'SET_FORM_FALSE';
export const SELECTED_KEG = 'SELECTED KEG';
export const SET_KEG_NULL = 'SET_KEG_NULL';
export const EDITING = 'EDITING';
export const EDITING_SET_FALSE = 'EDITING_SET_FALSE'
export const EDIT_KEG = 'EDIT_KEG'